import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const APPS_DIR = join(process.cwd(), "apps");
const MANIFEST_PATH = join(APPS_DIR, "_manifest.ts");

function identifierFor(slug: string): string {
  return `app_${slug.replace(/[^A-Za-z0-9_]/g, "_")}`;
}

function slugs(): string[] {
  return readdirSync(APPS_DIR)
    .filter((file) => file.endsWith(".ts") && file !== "_manifest.ts")
    .map((file) => file.slice(0, -".ts".length))
    .sort();
}

function render(appSlugs: string[]): string {
  const imports = appSlugs
    .map((slug) => `import ${identifierFor(slug)} from "./${slug}";`)
    .join("\n");
  const entries = appSlugs
    .map((slug) => `  ${JSON.stringify(slug)}: ${identifierFor(slug)},`)
    .join("\n");

  return `// AUTO-GENERATED by scripts/sync-apps.ts — do not edit by hand.
// Regenerated by the npm "predev" and "prebuild" hooks.
import type { AppConfig } from "@/lib/defineApp";
${imports ? `\n${imports}\n` : ""}
export const appManifest: Record<string, AppConfig> = {
${entries}
};
`;
}

const contents = render(slugs());
let previous = "";
try {
  previous = readFileSync(MANIFEST_PATH, "utf8");
} catch {
  previous = "";
}

if (previous !== contents) {
  writeFileSync(MANIFEST_PATH, contents);
  console.log(`sync-apps: wrote apps/_manifest.ts`);
} else {
  console.log("sync-apps: apps/_manifest.ts already up to date");
}
