// AUTO-GENERATED by scripts/sync-apps.ts — do not edit by hand.
// Regenerated by the npm "predev" and "prebuild" hooks.
import type { AppConfig } from "@/lib/defineApp";

import app_disputes from "./disputes";
import app_flags from "./flags";
import app_kyc from "./kyc";
import app_refunds from "./refunds";

export const appManifest: Record<string, AppConfig> = {
  "disputes": app_disputes,
  "flags": app_flags,
  "kyc": app_kyc,
  "refunds": app_refunds,
};
